remark: modified augmentations, only on old data, no messidor.
fold: 1
total_folds: 7
size: 456
top_lr: 5e-5
class_weights: None
cw_sampling: False
he_sampling: False
hard_ex_weight: 2
hard_df: weights/118_efficientnet-b5_f1_postraug2/diff.csv
num_samples: None
model_name: efficientnet-b5
ext_text: test
mean: (0.485, 0.456, 0.406)
std: (0.229, 0.224, 0.225)
resume: False
pretrained: False
pretrained_path: weights/108_efficientnet-b5_f1_ostraug/ckpt10.pth
resume_path: weights/
df_path: data/train_old.csv
data_folder: data/npy_files/bgcc456
phases: ["train", "val", "val_new"]
batch_size:
    train: 4
    val: 4
    val_new: 4
num_workers: 12
num_classes: 1
ep2unfreeze: 3
num_epochs: 40
base_lr: None
momentum: 0.95
patience: 4
tc_dups: False # take care of dups
dups_wsd: data/npy_files/dups_with_same_diagnosis.npy
bad_idx: data/npy_files/bad_train_indices.npy
sample: True
count_dict:
    0: 8000
    2: 5292
    1: 2443
    3: 873
    4: 708
messidor_in_train: False
mes_df: data/train_messidor.csv
