remark: training on new data + old samples 2k per class, with PP1
home: /media/ags/DATA/CODE/kaggle/aptos2019-blindness-detection/
#home: /home/eee/ug/15084015/aptos/
fold: 1
total_folds: 5
size: 256
top_lr: 5e-5
class_weights: None
cw_sampling: False
he_sampling: False
hard_ex_weight: 2
hard_df: weights/118_efficientnet-b5_f1_postraug2/diff.csv
num_samples: None
model_name: efficientnet-b5
ext_text: test
mean: (0.485, 0.456, 0.406)
std: (0.229, 0.224, 0.225)
pretrained: False
pretrained_path: weights/178_efficientnet-b5_f1_omag/ckpt19.pth
df_path: data/train.csv
old_df_path: data/2015.csv
data_folder: data/all_images/
#data_folder: data/npy_files/bgcc456
phases: ["train", "val"]
batch_size:
    train: 8
    val: 4
num_workers: 12
num_classes: 1
ep2unfreeze: 2
num_epochs: 20
base_lr: None
momentum: 0.95
patience: 4
tc_dups: True # take care of dups
dups_wsd: data/npy_files/good_duplicates.npy
bad_idx: data/npy_files/all_bad_duplicates.npy
sample: False
count_dict:
    0: 15000
    2: 13153
    1: 6205
    3: 2087
    4: 1914
messidor_in_train: False
mes_df: data/train_messidor.csv
add_old_samples: True
sample_dict:
    0: 1900
    2: 1900
    1: 1900
    3: 1900
    4: 1900

